dist: xenial
language: python
python: '2.7'
sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt
install:
  - pip install ansible
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
script:
  - ansible-playbook -v -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -v -i tests/inventory tests/test.yml --connection=local --sudo
  - ansible-playbook -v -i tests/inventory tests/test.yml --check --diff --connection=local --sudo
  - "echo 'Sleeping 60 while agent checks in initially and creates .audit.'; sleep 60"
  - "ansible-playbook -v -i tests/inventory tests/test.yml --connection=local --sudo |
    tee /tmp/output.txt; grep -q 'changed=0.*failed=0' /tmp/output.txt && (echo 'Idempotence test: pass' && exit 0) ||
    (echo 'Idempotence test: fail' && exit 1)"

env:
  global:
    secure: "iCi7Uja9PDxhtJHBSHHxZi8Awj0b/mfdlRdIHLDx51iONQlV4YLfPn/aTx4nD8a91V0WZqg11APIjZZxW/ViuU23qwgUB4MQ80QAn2mL3jRkXzmc9gQR3OZZd9KsPHTFUAOYMbenNFSTYS/PIZykkU6PsAydIe9dZTvLOrozD3I="
