---

# Cloudsight Setup
- name: Create Threat Stack Config Directory
  file: path="{{ threatstack_config_dir }}" state=directory owner=root group=root mode=0644 recurse=yes

- name: Create ThreatStack Config File
  template:
    src: config.j2
    dest: "{{ threatstack_config }}"
    owner: root
    group: root
    mode: 0644

- name: Cloudsight - setup default
  command: cloudsight setup --config="{{ threatstack_config }}" {{ threatstack_agent_extra_args }}
  register: setup_result
  args:
    creates: /opt/threatstack/cloudsight/config/.audit

- name: Create file to track extra Cloudsight config
  copy:
    content: "{{ threatstack_agent_config_args }}"
    dest: /opt/threatstack/cloudsight/config/.config_args
    owner: root
    group: root
    mode: 0644
  when: threatstack_agent_config_args|default(None) != None
  register: config_args

- name: Configure extra cloudsight parameters
  command: "cloudsight config {{ threatstack_agent_config_args }}"
  when: config_args.changed
  notify: restart cloudsight

# NOTE: We do not signal the cloudsight service to restart because the package
# takes care of this.  The workflow differs between fresh installation
# installation and upgrades.
- name: Test cloudsight state
  service:
    name: cloudsight
    enabled: yes
    state: started
