---
- name: Check if agent is v1.x
  set_fact:
    threatstack_v1_string: "{{ threatstack_pkg | regex_search('agent[=-]1\\.') }}"

- name: Define v1 variable
  set_fact:
    threatstack_v1: "{{ threatstack_v1_string != '' }}"

- name: Ensure agent_type is defined
  fail:
    msg: "threatstack_feature_plan is mandatory for 1.x agents!"
  when:
    - threatstack_v1
    - agent_type == ''